[profile.release]
lto = true
opt-level='z'

[workspace]
members=[
    "algorithms/graph/shortest_path/astar",
    "algorithms/graph/shortest_path/dijkstras",
    "algorithms/graph/minimum_spanning_tree/kruskals",
    "data_structures"
]