[package]
name = "data_structures"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-snip = {version = "0.4.0", default-features = false}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path="graph.rs"