name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack
      run: sh -c "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh" | cargo install cargo-workspaces | cargo update --verbose
    - name: Build
      run: cargo ws exec --no-bail wasm-pack build
    - name: Run tests
      run: cargo ws exec wasm-pack test --node
